# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# bool2str.rb
#

# ---- original file header ----
#
# @summary
#       Converts a boolean to a string using optionally supplied arguments. The
#    optional second and third arguments represent what true and false will be
#    converted to respectively. If only one argument is given, it will be
#    converted from a boolean to a string containing 'true' or 'false'.
#
#    *Examples:*
#
#    bool2str(true)                    => 'true'
#    bool2str(true, 'yes', 'no')       => 'yes'
#    bool2str(false, 't', 'f')         => 'f'
#
#    Requires a single boolean as an input.
#
#
Puppet::Functions.create_function(:'stdlib::bool2str') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    

    unless arguments.size == 1 or arguments.size == 3
      raise(Puppet::ParseError, "bool2str(): Wrong number of arguments " +
                                "given (#{arguments.size} for 3)")
    end

    value = arguments[0]
    true_string = arguments[1] || 'true'
    false_string = arguments[2] || 'false'
    klass = value.class

    # We can have either true or false, and nothing else
    unless [FalseClass, TrueClass].include?(klass)
      raise(Puppet::ParseError, 'bool2str(): Requires a boolean to work with')
    end

    unless [true_string, false_string].all?{|x| x.kind_of?(String)}
      raise(Puppet::ParseError, "bool2str(): Requires strings to convert to" )
    end

    return value ? true_string : false_string
  
  end
end
