# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#       Load a YAML file containing an array, string, or hash, and return the data
#    in the corresponding native data type.
#
#    For example:
#
#        $myhash = loadyaml('/etc/puppet/data/myhash.yaml')
#
#
Puppet::Functions.create_function(:'stdlib::loadyaml') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    unless args.length == 1
      raise Puppet::ParseError, ("loadyaml(): wrong number of arguments (#{args.length}; must be 1)")
    end

    if File.exists?(args[0]) then
      YAML.load_file(args[0])
    else
      warning("Can't load " + args[0] + ". File does not exist!")
      nil
    end

  
  end
end
